### ISSUE TITLE
Test folder

### ISSUE THREAD

**Issue by lgilpin** [lgilpin/anomaly-explain#1]
Organize unit tests into a single folder (with imports).

**Comment by vspenubarthi** [comment]
Vishnu's ToDo to Move Over:

- [ ] Make a copy of all the tests (that you see) and move them over to the Tests Folder
- [ ] For each of the tests
  * Run it in its native folder to make sure they work
  * Change the imports to make sure that they work in the tests folder
- [ ] Do Final test at the end to make sure that all the imports work for all of them in the folder
- [ ] Create master level `test.py` that will automate the testing process and give updates.

**Comment by vspenubarthi** [comment]
I will use the issue to track things I run into

**Comment by vspenubarthi** [comment]
* ConceptNet not installed by default, have to install ourself

Seems like a good number of tests still need to to be fleshed out so I will create the framework so we can develop them right in the test folder so we don't have to move them over later

**Comment by vspenubarthi** [comment]
I am slowly moving tests that currently work into the system_tests folder. When we have time, we should figure out which ones to move and when/how
